apiVersion: v1
kind: Pod
metadata:
  name: spring-starbucks-worker
  namespace: default
  labels:
    name: spring-starbucks-worker
spec:
  restartPolicy: Always
  containers:
    - image: juliancolumbres/spring-starbucks-worker
      name: spring-starbucks-worker
      env:
      - name: MYSQL_HOST
        value: "10.64.64.3"
      - name: MYSQL_USERNAME
        value: "gkeusername"   
      - name: MYSQL_PASSWORD
        value: "gkepassword"  
      - name: RABBIT_HOST
        value: "10.104.9.94"  
      - name: RABBIT_USERNAME
        value: "gkeusername"  
      - name: RABBIT_PASSWORD
        value: "gkepassword"   
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP